---
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    networks:
      - bookstack-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - APP_URL=https://bookstack.bensnetwork.de
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=nl8kbJZBAY81U
      - DB_DATABASE=bookstack
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/bgoeb/bookstack/data/:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    networks:
      - bookstack-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=mysqlrootpw
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=nl8kbJZBAY81U
    volumes:
      - /home/bgoeb/bookstack/data/:/config
      - /home/bgoeb/bookstack/backup/:/backup
    restart: unless-stopped

networks:
  bookstack-network:
    external: true
